name: Deployment of the API

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unittests:
    name: Unittests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Clean old environment
        run: make clean

      - name: Run unittests
        run: make tests-unittests
