name: Deployment of the API after merging into master.

on:
  push:
    branches: [master]

jobs:
  deploy_api:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Run unittests
        run: make deploy-api
