name: Running tests for the Pull Requests

on: pull_request

jobs:
  unit_tests:
    name: Unittests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Run unittests
        run: make tests-unittests

  # integration_or_e2e_tests: TODO - deploying an app on AWS and running some real API requests
